/**
 * © 2015 Cedexis Inc.
 * Radar JavaScript client
 * Application Version: 0.1.288
 * Build Timestamp: 1455929300
 */
(function(window,document){'use strict';var p={"true":!0};window.cedexis=window.cedexis||{};window.cedexis.radar=window.cedexis.radar||{};window.radar=window.radar||{};window.cdx=window.cdx||{};
function q(a){this.window=a.window;this.document=a.document;this.zoneId=a.R;this.customerId=a.C;this.createdAt=(new Date).getTime();this.domains={code:a.L,init:a.I,report:a.N};this.runCalledAt=0;this.sendPLT=a.O in p;this.startDelay=a.P;this.masterSampleRate=a.J;this.pltSampleRate=a.K;this.remoteProbingSampleRate=a.M;this.sendParentMessages=!1;t(this,"startDelay","radar-start-delay");t(this,"masterSampleRate","radar-master-sample-rate");t(this,"pltSampleRate","radar-plt-sample-rate");t(this,"remoteProbingSampleRate",
"radar-remote-probing-sample-rate");t(this,"sendParentMessages","radar-send-parent-messages");this.includePartnerTags=a.H in p;this.buildTimestamp=a.B;this.h=[];this.api={requestor:this,zoneId:this.zoneId,customerId:this.customerId,extend:function(a,c){this[a]=c}};this.c=function(a){return/radar-no-ajax/i.test(a.location.search)?!1:a.XMLHttpRequest&&"undefined"!==typeof(new a.XMLHttpRequest).withCredentials?!0:!1}(a.window);this.plugins=[];this.u=null}q.prototype.browserHasCorsSupport=function(){return this.c};
function t(a,b,c){if(1<a.window.location.search.length)for(var d=a.window.location.search.slice(1).split("&"),k=d.length;k--;){var l=d[k].split("=");if(2===l.length&&c===l[0])if(l=parseInt(l[1],10),isNaN(l))a.log("Warning: "+c+" should be set to a number");else{switch(b){case "masterSampleRate":case "remoteProbingSampleRate":case "pltSampleRate":l/=100;break;case "startDelay":l*=1E3;break;case "sendParentMessages":l=0<l?!0:!1}a[b]=l;a.log(b+" set to "+l)}}}
q.prototype.log=function(a){(this.window.console||{log:function(){}}).log(a)};
q.prototype.w=function(){return{a:this.c?"1":"0",b:function(a){a=a.createElement("script");return a.addEventListener?"2":a.readyState?"1":"0"}(this.document),l:"function"!==typeof Object.keys?"1":"0",n:function(a,b){if(/msie/i.test(a.navigator.userAgent))if(void 0!==b.documentMode){if(9>b.documentMode)return"0"}else if("BackCompat"===b.compatMode)return"0";return void 0===a.performance?"0":"1"}(this.window,this.document),p:function(a){return"function"===typeof a.postMessage&&"function"===typeof a.addEventListener?
"1":"0"}(this.window),t:/(iphone|ipad|android|iemobile|opera mini|ucbrowser|blackberry)/i.test(this.window.navigator.userAgent)?"0":"1",r:function(a){var b;if(b=a.performance&&"function"===typeof a.performance.getEntriesByType)a=/msie (\d+)/i.exec(a.navigator.userAgent),b=!(a&&10>=parseInt(a[1],10));return b?"1":"0"}(this.window),imagesok:"1"}};q.prototype.deviceCaps=q.prototype.w;
function v(){var a=w.window.navigator.userAgent;if("Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"===a)return!0;for(var b=[/opera mini/i,/skyfire/i,/teashark/i,/uzard/i,/puffin/i,/yabrowser/i],c=b.length;c--;)if(b[c].test(a))return!0;return!1}
function y(){var a={V:/keynote/i,W:/ KTXN /,T:/gomez/i,S:/catchpoint/i,X:/pingdom/i,U:/ip-label/,Y:/witbe-/i},b,c,d;b=window.cedexis.radar.allowed_monitoring_agents||[];c=function(a){var c,d;for(c=0;c<b.length;c+=1)if(d=b[c].toLowerCase(),d===a)return!0;return!1};for(d in a)if(a.hasOwnProperty(d)&&a[d].test(window.navigator.userAgent)&&!c(d))return!0;return!1}
q.prototype.m=function(a,b){for(var c=this.window.cedexis.main,d=this.window.navigator,k=a+":"+c.y64enc(z(b)),l=[this.domains.report,"n1"],n=22;n--;)l.push(0);if("function"===typeof d.sendBeacon&&this.requestSignature&&this.requestSignatureTimestamp&&12E4>(new Date).getTime()-this.requestSignatureTimestamp)l.push(this.requestSignature),l.push(k),l.push(0),d.sendBeacon("//"+l.join("/"));else if(c&&"doInitWithCallback"in c&&this.c){var r=this;c.doInitWithCallback(this,function(){return function(){if(this.responseText){var a=
/<requestSignature>([^<]+)/.exec(this.responseText);a&&a[1]&&(l.push(a[1]),l.push(k),l.push(0),r.window.cedexis.main.send_report("//"+l.join("/")))}}}())}};q.prototype.plt_ex=q.prototype.m;q.prototype.impact=function(a){this.window.cedexis&&this.window.cedexis.main?this.m("impact_kpi",a):this.h.push(a)};q.prototype.afterRun=function(){for(var a=10;a--&&0<this.h.length;)this.m("impact_kpi",this.h.shift())};
q.prototype.v=function(a){if(this.window.XMLHttpRequest){var b=new this.window.XMLHttpRequest;if("undefined"!==typeof b.withCredentials){var c=a.method.toUpperCase();try{b.open(c,a.url,!0);var d=a.headers||{},k;for(k in d)d.hasOwnProperty(k)&&b.setRequestHeader(k,d[k]);"POST"===c?b.send(a.data):b.send()}catch(l){}}}};q.prototype.ajax=q.prototype.v;
q.prototype.f1=function(a){this.requestSignature&&this.v({method:"get",url:["//rpt.cedexis.com/f1",this.requestSignature,a.providerOwnerZoneId,a.providerOwnerCustomerId,a.providerId,a.probeTypeId,a.resultCode,a.measurement].join("/")})};q.prototype.addPlugin=function(a){for(var b=0;b<this.plugins.length;b++)if(a===this.plugins[b])return;this.plugins.push(a)};q.prototype.notify=function(a){for(var b=0;b<this.plugins.length;b++){var c=this.plugins[b];"function"===typeof c.notify&&c.notify(a)}};
q.prototype.setImpactObject=function(a){this.u=a};q.prototype.getImpactObject=function(){return this.u};
function z(a){function b(a,b){for(var k="",l=0;l<a.length;l++)k=b(k,a[l],l);return k}switch(typeof a){case "string":return'"'+(""+a).replace(/\"/g,'\\"')+'"';case "number":return isNaN(a)?"null":a;case "boolean":return a?"true":"false";case "undefined":return"null";default:return null===a?"null":""+a!==a&&"[object Array]"==Object.prototype.toString.call(a)?"["+b(a,function(a,b){return a+","+z(b)}).substring(1)+"]":"{"+b(function(a){var b=[],k;for(k in a)b.push(k);return b}(a),function(b,d){void 0!==
a[d]&&"function"!==typeof a[d]&&(b+=","+z(d)+":"+z(a[d]));return b}).substring(1)+"}"}}window.cedexis.jsonEncode=z;function A(a,b){for(var c=a.length;c--;)if(b===a[c])return!0;return!1}window.cedexis.arrayContains=A;/*
 Copyright (c) 2010 Nick Galbreath
 http://code.google.com/p/stringencoders/source/browse/#svn/trunk/javascript

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/
var B={j:"-",ALPHA:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._",o:function(){try{return new DOMException}catch(b){var a=Error("DOM Exception 5");a.code=a.c=5;a.name=a.description="INVALID_CHARACTER_ERR";a.toString=function(){return"Error: "+a.name+": "+a.message};return a}},G:function(a,b){var c=B.ALPHA.indexOf(a.charAt(b));if(-1===c)throw B.o();return c},decode:function(a){a=""+a;var b=B.G,c,d,k,l=a.length;if(0===l)return a;if(0!==l%4)throw B.o();c=0;a.charAt(l-1)===B.j&&(c=
1,a.charAt(l-2)===B.j&&(c=2),l-=4);var n=[];for(d=0;d<l;d+=4)k=b(a,d)<<18|b(a,d+1)<<12|b(a,d+2)<<6|b(a,d+3),n.push(String.fromCharCode(k>>16,k>>8&255,k&255));switch(c){case 1:k=b(a,d)<<18|b(a,d+1)<<12|b(a,d+2)<<6;n.push(String.fromCharCode(k>>16,k>>8&255));break;case 2:k=b(a,d)<<18|b(a,d+1)<<12,n.push(String.fromCharCode(k>>16))}return n.join("")},F:function(a,b){var c=a.charCodeAt(b);if(255<c)throw B.o();return c},encode:function(a){if(1!==arguments.length)throw new SyntaxError("Not enough arguments");
var b=B.j,c=B.ALPHA,d=B.F,k,l,n=[];a=""+a;var r=a.length-a.length%3;if(0===a.length)return a;for(k=0;k<r;k+=3)l=d(a,k)<<16|d(a,k+1)<<8|d(a,k+2),n.push(c.charAt(l>>18)),n.push(c.charAt(l>>12&63)),n.push(c.charAt(l>>6&63)),n.push(c.charAt(l&63));switch(a.length-r){case 1:l=d(a,k)<<16;n.push(c.charAt(l>>18)+c.charAt(l>>12&63)+b+b);break;case 2:l=d(a,k)<<16|d(a,k+1)<<8,n.push(c.charAt(l>>18)+c.charAt(l>>12&63)+c.charAt(l>>6&63)+b)}return n.join("")}};B.encode=B.encode;window.cedexis=window.cedexis||{};
window.cedexis.base64=B;/*
 JavaScript MD5
 https://github.com/blueimp/JavaScript-MD5

 Copyright 2011, Sebastian Tschan
 https://blueimp.net

 Licensed under the MIT license:
 http://www.opensource.org/licenses/MIT

 Based on
 A JavaScript implementation of the RSA Data Security, Inc. MD5 Message
 Digest Algorithm, as defined in RFC 1321.
 Version 2.2 Copyright (C) Paul Johnston 1999 - 2009
 Other contributors: Greg Holt, Andrew Kepert, Ydnar, Lostinet
 Distributed under the BSD License
 See http://pajhome.org.uk/crypt/md5 for more info.
*/
window.cedexis=window.cedexis||{};
(function(a){function b(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535}function c(a,c,m,d,k,l){a=b(b(c,a),b(d,l));return b(a<<k|a>>>32-k,m)}function d(a,b,m,d,k,l,n){return c(b&m|~b&d,a,b,k,l,n)}function k(a,b,m,d,k,l,n){return c(b&d|m&~d,a,b,k,l,n)}function l(a,b,m,d,k,l,n){return c(m^(b|~d),a,b,k,l,n)}function n(a,x){a[x>>5]|=128<<x%32;a[(x+64>>>9<<4)+14]=x;var m,n,r,F,u,e=1732584193,f=-271733879,g=-1732584194,h=271733878;for(m=0;m<a.length;m+=16)n=e,r=f,F=g,u=h,e=d(e,
f,g,h,a[m],7,-680876936),h=d(h,e,f,g,a[m+1],12,-389564586),g=d(g,h,e,f,a[m+2],17,606105819),f=d(f,g,h,e,a[m+3],22,-1044525330),e=d(e,f,g,h,a[m+4],7,-176418897),h=d(h,e,f,g,a[m+5],12,1200080426),g=d(g,h,e,f,a[m+6],17,-1473231341),f=d(f,g,h,e,a[m+7],22,-45705983),e=d(e,f,g,h,a[m+8],7,1770035416),h=d(h,e,f,g,a[m+9],12,-1958414417),g=d(g,h,e,f,a[m+10],17,-42063),f=d(f,g,h,e,a[m+11],22,-1990404162),e=d(e,f,g,h,a[m+12],7,1804603682),h=d(h,e,f,g,a[m+13],12,-40341101),g=d(g,h,e,f,a[m+14],17,-1502002290),
f=d(f,g,h,e,a[m+15],22,1236535329),e=k(e,f,g,h,a[m+1],5,-165796510),h=k(h,e,f,g,a[m+6],9,-1069501632),g=k(g,h,e,f,a[m+11],14,643717713),f=k(f,g,h,e,a[m],20,-373897302),e=k(e,f,g,h,a[m+5],5,-701558691),h=k(h,e,f,g,a[m+10],9,38016083),g=k(g,h,e,f,a[m+15],14,-660478335),f=k(f,g,h,e,a[m+4],20,-405537848),e=k(e,f,g,h,a[m+9],5,568446438),h=k(h,e,f,g,a[m+14],9,-1019803690),g=k(g,h,e,f,a[m+3],14,-187363961),f=k(f,g,h,e,a[m+8],20,1163531501),e=k(e,f,g,h,a[m+13],5,-1444681467),h=k(h,e,f,g,a[m+2],9,-51403784),
g=k(g,h,e,f,a[m+7],14,1735328473),f=k(f,g,h,e,a[m+12],20,-1926607734),e=c(f^g^h,e,f,a[m+5],4,-378558),h=c(e^f^g,h,e,a[m+8],11,-2022574463),g=c(h^e^f,g,h,a[m+11],16,1839030562),f=c(g^h^e,f,g,a[m+14],23,-35309556),e=c(f^g^h,e,f,a[m+1],4,-1530992060),h=c(e^f^g,h,e,a[m+4],11,1272893353),g=c(h^e^f,g,h,a[m+7],16,-155497632),f=c(g^h^e,f,g,a[m+10],23,-1094730640),e=c(f^g^h,e,f,a[m+13],4,681279174),h=c(e^f^g,h,e,a[m],11,-358537222),g=c(h^e^f,g,h,a[m+3],16,-722521979),f=c(g^h^e,f,g,a[m+6],23,76029189),e=c(f^
g^h,e,f,a[m+9],4,-640364487),h=c(e^f^g,h,e,a[m+12],11,-421815835),g=c(h^e^f,g,h,a[m+15],16,530742520),f=c(g^h^e,f,g,a[m+2],23,-995338651),e=l(e,f,g,h,a[m],6,-198630844),h=l(h,e,f,g,a[m+7],10,1126891415),g=l(g,h,e,f,a[m+14],15,-1416354905),f=l(f,g,h,e,a[m+5],21,-57434055),e=l(e,f,g,h,a[m+12],6,1700485571),h=l(h,e,f,g,a[m+3],10,-1894986606),g=l(g,h,e,f,a[m+10],15,-1051523),f=l(f,g,h,e,a[m+1],21,-2054922799),e=l(e,f,g,h,a[m+8],6,1873313359),h=l(h,e,f,g,a[m+15],10,-30611744),g=l(g,h,e,f,a[m+6],15,-1560198380),
f=l(f,g,h,e,a[m+13],21,1309151649),e=l(e,f,g,h,a[m+4],6,-145523070),h=l(h,e,f,g,a[m+11],10,-1120210379),g=l(g,h,e,f,a[m+2],15,718787259),f=l(f,g,h,e,a[m+9],21,-343485551),e=b(e,n),f=b(f,r),g=b(g,F),h=b(h,u);return[e,f,g,h]}function r(a){var b,c="";for(b=0;b<32*a.length;b+=8)c+=String.fromCharCode(a[b>>5]>>>b%32&255);return c}function u(a){var b,c=[];c[(a.length>>2)-1]=void 0;for(b=0;b<c.length;b+=1)c[b]=0;for(b=0;b<8*a.length;b+=8)c[b>>5]|=(a.charCodeAt(b/8)&255)<<b%32;return c}function G(a){return r(n(u(a),
8*a.length))}function H(a,b){var c,d=u(a),k=[],l=[];k[15]=l[15]=void 0;16<d.length&&(d=n(d,8*a.length));for(c=0;16>c;c+=1)k[c]=d[c]^909522486,l[c]=d[c]^1549556828;c=n(k.concat(u(b)),512+8*b.length);return r(n(l.concat(c),640))}function I(a){var b="",c,d;for(d=0;d<a.length;d+=1)c=a.charCodeAt(d),b+="0123456789abcdef".charAt(c>>>4&15)+"0123456789abcdef".charAt(c&15);return b}a.md5=function(a,b,c){return b?c?H(unescape(encodeURIComponent(b)),unescape(encodeURIComponent(a))):I(H(unescape(encodeURIComponent(b)),
unescape(encodeURIComponent(a)))):c?G(unescape(encodeURIComponent(a))):I(G(unescape(encodeURIComponent(a))))}})(window.cedexis);function C(a){this.f=[];if(a)for(this.f.push({D:a,state:0,i:[this]}),a=0;a<this.f.length;a++)setTimeout(D(this.f[a]),1)}var E={0:{name:"PENDING"},1:{name:"FULFILLED"},2:{name:"REJECTED"}};function J(a){for(var b=[],c=0;c<a.f.length;c++){var d=a.f[c];if(1!==d.state)return;b.push(d.value)}(a=K(a,b))&&setTimeout(a,1)}function K(a,b){if(a.c){var c=a.c;return function(){c(b)}}return null}function D(a){var b=L(a),c=M(a);return function(){try{a.D(b,c)}catch(d){c(d)}}}
function L(a){return function(b){if(0!==a.state)throw Error("Attempted to resolve a promise in the "+E[a.state].name+" state");a.state=1;a.value=b;for(b=0;b<a.i.length;b++)J(a.i[b])}}function M(a){function b(a,b){return function(){a(b)}}return function(c){if(0!==a.state)throw Error("Attempted to resolve a promise in the "+E[a.state].name+" state");a.state=2;a.error=c;for(var d=0;d<a.i.length;d++){var k=a.i[d];k.A&&setTimeout(b(k.A,c),1);k.s&&setTimeout(b(k.s,c),1)}}}
C.prototype.then=function(a,b){this.c=a;this.A=b;return this};C.prototype["catch"]=function(a){this.s=a;return this};C.all=function(a){for(var b=new C,c=b.f,d=0;d<a.length;d++)for(var k=a[d].f,l=0;l<k.length;l++){var n=k[l];n.i.push(b);c.push(n)}J(b);return b};window.cedexis=window.cedexis||{};window.cedexis.Promise=window.cedexis.Promise||C;function N(a){this.window=a;this.g={};this.c=-1}N.prototype.setBufferSize=function(a){if("number"===typeof a&&0<a&&this.c<a){this.c=a;var b=O(this);if(b){var c=b.setResourceTimingBufferSize||b.webkitSetResourceTimingBufferSize;c&&c.call(b,a)}}};
N.prototype.setToClearOnBufferFull=function(a){var b=O(this);b&&a&&!this.h&&(a=this.h=P(),b.addEventListener&&"undefined"!==typeof b.onresourcetimingbufferfull?b.addEventListener("resourcetimingbufferfull",a,!1):b.addEventListener&&"undefined"!==typeof b.onwebkitresourcetimingbufferfull&&b.addEventListener("webkitresourcetimingbufferfull",a,!1))};
N.prototype.makeManagerProxy=function(a,b){return{g:this.g,add:function(c){var d=this.g[a]=this.g[a]||{};(d[b]=d[b]||[]).push(c)},contains:function(c){var d=this.g[a]=this.g[a]||{},d=d[b]=d[b]||[];return A(d,c)}}};function P(){return function(){var a=this.clearResourceTimings||this.webkitClearResourceTimings;a&&a.call(this)}}function O(a){return"performance"in a.window?a.window.performance:null}window.cedexis=window.cedexis||{};
window.cedexis.resourceTimingManager=window.cedexis.resourceTimingManager||new N(window);var w=new q({window:window,document:document,R:"1",C:"19300",L:"radar.cedexis.com",I:"cedexis-radar.net",N:"rpt.cedexis.com",O:"true",P:parseInt("2000",10),J:parseFloat("1"),K:parseFloat("1"),M:parseFloat("1"),H:"true",B:parseInt("1455929300",10)}),Q=window.cedexis;Q.requestors=Q.requestors||{};
if(Math.random()<w.masterSampleRate){Q.requestors["1;19300"]=w;var R;if(!(R=v())){var S;if(S=y())S=!/radar-allow-monitors=1/.test(w.window.location.search);R=S}R||setTimeout(function(){var a=w;"function"===typeof a.window.cedexisInit&&a.window.cedexisInit(a.api);var b=/cedexisInit(\d+)/,c;for(c in a.window){var d=b.exec(c);if(d&&a.customerId==d[1]&&"function"===typeof a.window[d[0]])a.window[c](a.api)}a=w;(c=a.window.crypto||a.window.msCrypto)&&c.getRandomValues?
(b=new Uint32Array(1),c.getRandomValues(b),b=b[0]):b=0;a.transactionId=b||Math.floor(1E9*Math.random());var b=a.w(),d=c="",k;for(k in b)b.hasOwnProperty(k)&&(d+=c+k+"="+b[k],c="&");k="//"+a.domains.code+"/"+a.buildTimestamp+"/radar/main.js?"+d;a:{if(0<a.window.location.search.length){b=a.window.location.search.slice(1).split("&");c=[];for(d=b.length;d--;)"providers=all"===b[d]&&c.push(b[d]);c=c.join("&");if(0<c.length){b="&"+c;break a}}b=""}k=k+b;b=a.document.getElementById("cdx");b||
(b=a.document.createElement("div"),b.id="cdx",a.document.body.appendChild(b));a=a.document.createElement("script");a.type="text/javascript";a.async=!0;a.src=k;b.appendChild(a)},w.startDelay)};}(window,document));(function(){'use strict';(function(){function d(a,b,c,e,g,f){this.a=a;this.c=b;this.s=c;this.o=e;this.b=f;this.U=this.T=this.m=this.g=this.h=null;this.i="";this.H=[];this.J=[];this.V=!1;this.W=!!f.enableNewReporting;this.v={};this.Z=this.lb(g);this.S=!1;this.K=[];this.ba=this.pb();this.L=[];this.Y=!1;this.Fb=[];this.X=d.prototype.ab;this.ca="r1";this.Db=0;this.$=this.R=!1}function n(a,b,c){this.c=a;this.a=b;this.b=0;this.b="number"===typeof c?c:b}function l(){this.f=this.a=this.b=this.c=null}function k(){this.c=
this.f=this.a=this.b=void 0}function m(){for(var a=[],b=0;32>b;b+=1)a.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random())+0));return a.join("")}function t(a){for(var b=0,c=a.length,e=0;e<c;e++)b+=a[e];return b/c}function u(a,b){var c=a.createElement("a");return c?(c.href=b,{protocol:c.protocol,host:c.host,pathname:c.pathname,search:c.search}):null}d.b="4.0.0";d.a="responseEnd responseStart requestStart connectEnd secureConnectionStart connectStart domainLookupEnd domainLookupStart redirectEnd redirectStart".split(" ");
window.cedexis=window.cedexis||{};window.cedexis.classes=window.cedexis.classes||{};window.cedexis.classes.ImpactKpisPlugin4=d;d.prototype.fa=function(a){return a+this.s+"_"+this.o};d.prototype.w=function(){return this.fa("cdx_ses_")};d.prototype.eb=function(){return this.fa("cdx_site_")};d.prototype.P=function(){return!!this.a.XMLHttpRequest};d.prototype.Xa=function(){return"performance"in this.a?this.a.performance:null};d.prototype.sb=function(){var a=this;return function(b){a.tb(b)}};d.prototype.makeWindowMessageHandler=
d.prototype.sb;d.prototype.tb=function(a){var b;try{b=JSON.parse(a.data)}catch(e){}if(b&&(a=b.cedexis)&&a.zoneId==this.s&&a.customerId==this.o&&(b=b.cedexis.providerDetection)){a="Error";if(200===b.httpStatus){a="Unknown";var c=/x-cdn-forward:\s*(\w+)/im.exec(b.headers);c&&c[1]&&(a=c[1])}this.v[b.hostname]=a}};d.prototype.yb=function(){this.Ea()&&(this.S=!0);this.R=!!this.b.alwaysSendPlt;var a=this.l();if(a){a.addPlugin(this);var b=this.cb();if(b){this.I=b;this.ub(b);this.V=!!b.enableMetadataReporting;
this.Ob(b);var c=b.includeOnlyForSites;if(c&&(!this.h||0>c.indexOf(this.h)))return;this.zb(b);this.Gb(b);this.Eb(b);this.Qb(b);c=this.Qa();this.W&&this.oa(c)}this.S&&((b=b&&"undefined"!==typeof this.I.resourceTimingConfig?this.I.resourceTimingConfig:this.b.defaultResourceTimingConfig)&&this.b.resourceTiming&&(b=this.b.resourceTiming[b])&&this.Da(b),b=!0,"boolean"===typeof this.b.legacyPerfDataReportEnabled&&(b=this.b.legacyPerfDataReportEnabled),b&&(this.aa=this.a.setInterval(this.mb(),500)));this.Aa();
this.ya();a.api.extend("reportKpi",this.nb());a.api.extend("impact",this.kb())}};d.prototype.kb=function(){var a=this;return function(b){console.log("Custom Impact Event:"+a.a.cedexis.jsonEncode(b))}};d.prototype.notify=function(a){"init"===a&&(this.Y=!0,this.na())};d.prototype.bb=function(){return"string"===typeof this.f.resourceTimingReportMethod?this.f.resourceTimingReportMethod:"string"===typeof this.b.defaultResourceTimingReportMethod?this.b.defaultResourceTimingReportMethod:"all"};d.prototype.Da=
function(a){this.f=a;"aggregated"===this.bb()&&(this.X=d.prototype.$a,this.ca="r2");a=this.f.resourceTimingBufferSize;if("number"===typeof a&&150<a){var b=this.Xa();if(b){var c=b.setResourceTimingBufferSize||b.webkitSetResourceTimingBufferSize;c&&c.call(b,a)}}if(a=this.f.sampleIntervals)this.log("Resource check intervals: "+JSON.stringify(a)),(a=a.shift())&&this.a.setTimeout(this.ba,a)};d.prototype.pb=function(){var a=this;return function(){a.gb()}};d.prototype.Oa=function(a){var b=this.c.createElement("script");
b.async=!0;var c;a.test?(c="",a.test.host&&(c="//"+a.test.host),c+=a.test.path||"/advert.js"):c="/advert.js";c+="?rnd="+m();b.src=c;this.c.body.appendChild(b)};d.prototype.Jb=function(){return void 0===this.a.notadblocker};d.prototype.Ga=function(a){var b=this;return function(){b.Jb()&&b.C(a.value,1)}};d.prototype.Ia=function(a){this.Oa(a);this.a.setTimeout(this.Ga(a),2E3)};d.prototype.l=function(){if(this.a.cedexis)return this.a.cedexis.requestors[this.s+";"+this.o]};d.prototype.run=d.prototype.yb;
d.prototype.log=function(a){this.b.debugging&&console.log(a)};d.prototype.Qa=function(){var a={};this.g&&(a.sessionID=this.A());this.m&&(a.category=this.m);0<this.i.length&&(a.source=this.i);0<this.H.length&&(a.kpi=this.H);this.V&&0<this.J.length&&(a.metadata=this.J);this.l().setImpactObject(a);this.a.JSON&&this.log("Impact: "+this.a.cedexis.jsonEncode(a));return a};d.prototype.cb=function(){var a=this.a.location.hostname+this.a.location.pathname,b=[],c;for(c in this.b.sites)this.b.sites.hasOwnProperty(c)&&
b.push(c);b.sort(function(a,b){return a.length>b.length?1:a.length<b.length?-1:0});for(c=b.length;c--;){var e=b[c];if(0===a.indexOf(e))return this.b.sites[e]}return this.b.defaultSite||null};d.prototype.Qb=function(a){if(this.b.sourceConfigs&&a.sourceConfig&&(a=this.b.sourceConfigs[a.sourceConfig])){var b=this.c.referrer;this.M("docref",b);var c=decodeURIComponent(this.a.location.search);this.M("qs",c);for(var e=0;e<a.length;e++){var d=a[e],f=d.rule;if(f)switch(f.type){case "anyReferrerDomain":case "referrerDomain":if(this.xa(d,
b))return;break;case "queryStringRegex":if(this.va(d,c))return;break;default:this.log("Unexpected source rule type: "+f.type)}}}};d.prototype.Aa=function(){if(this.P()&&this.a.JSON){var a=(this.I||{}).providerDetectionConfig||this.b.defaultProviderDetectionConfig,b=this.b.providerDetection;if(a&&b&&(a=b[a]))for(var b=Object.keys(a),c=0;c<b.length;c++){var e=b[c];this.log("Starting provider detection for: "+e);this.Ca(e,a[e])}}};d.prototype.ya=function(){if(this.P()&&this.a.JSON){var a=this.I||{};
if(a.layout&&(a=this.b.layouts[a.layout])&&a.reportPageHeaders){var b=new XMLHttpRequest;if(b)try{b.open("HEAD",this.a.location.href,!0),b.addEventListener("load",function(a,b){return function(){var d=this.getAllResponseHeaders();if(d){var d=d.split("\r\n").reduce(function(a,b){var c=b.indexOf(":"),e=[];e.push(b.slice(0,c));e.push(b.slice(c+1));e[1]=e[1].trim();e[0]&&e[1]&&a.push(e);return a},[]),f=b.reduce(function(a,b){for(var c=0;c<d.length;c++)b.toLowerCase()===d[c][0].toLowerCase()&&a.push(d[c]);
return a},[]);a.wb({pageHeaders:f})}}}(this,a.reportPageHeaders)),b.send()}catch(c){}}}};d.prototype.Ca=function(a,b){var c="//"+a+b.outerPath+"?p="+encodeURIComponent(b.innerPath)+"&z="+this.s+"&c="+this.o,e=this.c.createElement("iframe");e.style.display="none";e.src=c;this.ua(e)};d.prototype.ua=function(a){var b=this.c.getElementById("cdx");b||(b=this.c.createElement("div"),b.id="cdx",this.c.body.appendChild(b));b.appendChild(a)};d.prototype.va=function(a,b){if(b){var c=a.rule;if(c){var e=a.sourceFrom;
if("queryStringRegex"===c.type){var d;try{d=new RegExp(c.value)}catch(f){return this.log("Invalid regular expression"),!1}if(d)if("sourceProperty"===e){if(d.test(b))return this.i=a.source,!0}else if((d=d.exec(b))&&"matchGroup"===e&&(c=c.matchGroup,"undefined"!==c&&d[c]))return this.i=d[c],!0}}}return!1};d.prototype.xa=function(a,b){if(b){var c=a.rule,e;a:{if((e=b.split("//"))&&e[1]&&(e=e[1].split("/"))&&0<e.length){e=e[0];break a}e=null}if(e){if("anyReferrerDomain"===c.type&&(e!==this.a.location.hostname||
c.allowOwnHostname))return this.i=e,!0;if(e===c.value)switch(a.sourceFrom){case "sourceProperty":return this.i=a.source,!0;case "referrerDomain":return this.i=e,!0}}}return!1};d.prototype.Ob=function(a){var b=this.eb();this.h=this.u(b);a.site&&(this.h=a.site,this.D({name:b,value:this.h,path:a.cookie.path||null,domain:a.cookie.domain,B:null,G:a.cookie.secure,F:!1}));this.h&&this.H.push(["Site: "+this.h,!0])};d.prototype.ub=function(a){var b=this.u(this.w());!b&&(b=this.u("cdx_ses"))&&(this.pa(a,b),
this.D({name:"cdx_ses",value:"",path:a.cookie.path||null,domain:a.cookie.domain,B:null,G:a.cookie.secure,F:!0}))};d.prototype.zb=function(a){var b,c=this.ga();c?((new Date).getTime()-c.o())/6E4>=this.N("sessionTimeout",this.b,30)?(b=this.ka(),this.Ma(a)):(b=new n(c.s(),(new Date).getTime(),null),c=c.j(),isNaN(c)&&(c=b.a),b.g(c)):(b=this.ka(),this.j("new",!0));b.f()||b.g(b.a);c=new k;c.w(b.c);c.v(b.a);c.A(b.f());this.O(a,c);this.g=b.c};d.prototype.Ka=function(a){var b=a.filters;if(b&&b.length){a=this.ha(a.filters);
for(var b=!1,c=0;c<a.length;c++)if(this.qa(a[c])){b=!0;break}return b}return!0};d.prototype.Eb=function(a){var b=this.b.layouts[a.layout];if(b&&b.kpi)for(var c=0;c<b.kpi.length;c++){var e=b.kpi[c];if(this.Ka(e))switch(e.type){case "sessionLength":this.Mb(a,e);break;case "resourceInterval":this.Ib(e);break;case "URL":this.za(e);break;case "DOM":this.Ab(e);break;case "adBlockDetection":this.Ia(e);break;case "click":this.wa(e);break;case "scroll":this.Ba(e);break;case "any":case "ANY":this.j(e.value,
1);break;default:throw"setKpis "+e.type+" not understood";}}};d.prototype.Ba=function(a){var b=a.test;b&&"percentageOfDocument"===b.type&&"number"===typeof b.value&&a.value&&this.a.addEventListener("scroll",this.qb(a))};d.prototype.qb=function(a){function b(){c.c.body.scrollTop/(c.c.body.clientHeight-c.a.innerHeight)*100>=e&&(c.a.removeEventListener("scroll",b),c.C(a.value,1))}var c=this,e=a.test.value;return b};d.prototype.wa=function(a){if("function"===typeof this.c.querySelectorAll&&"selector"in
a){var b=this.c.querySelectorAll(a.selector);if(b&&b.length)for(var c=this.jb(a),e=0;e<b.length;e++){var d=b.item(e);if(d){var f=!0;a.innerHTML&&a.innerHTML!==d.innerHTML&&(f=!1);f&&d.addEventListener("click",c)}}}};d.prototype.jb=function(a){var b=this;return function(){b.C(a.value,1)}};d.prototype.za=function(a){var b=a.value,c=a.test;if(c){var e=c.type;if(e)if(a.force||(b="conversionPage"),"byPathRegex"===e){var d;if(c.ignoreCase)try{d=new RegExp(c.value,"i")}catch(f){this.log("Invalid regular expression)");
return}else try{d=new RegExp(c.value)}catch(f){this.log("Invalid regular expression");return}d.test(this.a.location.pathname)&&this.j(b,1)}else if("byPath"===c.type)c.value===this.a.location.pathname&&this.j(b,1);else if("byHash"===c.type)this.ra(c)&&this.j(b,1);else throw"setURLKpi "+c.type+" not understood";}};d.prototype.Ab=function(a){(a=a.test)&&"selector"in a&&"kpiFromValue"in a&&this.Cb(a.selector,a.kpiFromValue)};d.prototype.Wa=function(a,b){var c=a.matchGroup||0,e,d;try{e=new RegExp(a.value)}catch(p){return this.log("Invalid regular expression"),
null}e&&(d=e.exec(b));if(d&&d[c]){b=d[c];if("stripChars"in a){c=a.stripChars;e="";for(d=0;d<b.length;d++){for(var f=!1,h=0;h<c.length;h++)if(b[d]===c[h]||"number"===typeof c[h]&&b.charCodeAt(d)===c[h]){f=!0;break}f||(e+=b[d])}b=e}if("float"===a.convertTo){c="";for(e=0;e<b.length;e++)c+=","===b[e]?".":b[e];b=parseFloat(c);if(isNaN(b))return null}else"int"===a.convertTo&&(b=parseInt(b,10));return b}return null};d.prototype.Cb=function(a,b){if("function"===typeof this.c.querySelectorAll){var c=this.c.querySelectorAll(a);
if(c&&(c=c[0])&&(c=c.innerText||c.textContent)){this.M("setKpiFromDOMFromSelector",c);for(var e=0;e<b.length;e++){var d=b[e],f=this.Wa(d,c);if(null!==f){this.j(d.name,f);break}}}}};d.prototype.Mb=function(a,b){var c=this.ga();c&&c.a&&"1"!==c.f&&(c=this.hb(b.test.duration)-((new Date).getTime()-c.j()),1>c?(this.j(b.value,1),c=new k,c.g(),this.O(a,c)):this.a.setTimeout(this.rb(a,b),c))};d.prototype.rb=function(a,b){var c=this;return function(){var e=new k;e.g();c.O(a,e);c.C(b.value,1)}};d.prototype.hb=
function(a){a=a.split(" ");return a[1]&&/minute/.test(a[1])?Math.floor(6E4*parseFloat(a[0])):a[1]&&/second/.test(a[1])?Math.floor(1E3*parseFloat(a[0])):0};d.prototype.Ib=function(a){this.Hb=this.a.setInterval(this.ob(a),1E3)};d.prototype.ob=function(a){var b=this,c=(new Date).getTime();return function(){(12E3<(new Date).getTime()-c||b.Kb(a))&&b.xb(b.Hb)}};d.prototype.Kb=function(a){var b;switch(a.test.type){case "byPathRegex":b=this.Ya(a.test)}if(b){var c=b.duration;0<b.requestStart&&(c=Math.round(b[a.test.end]-
b[a.test.start]));c>=a.test.min&&this.C(a.value,c);return!0}return!1};d.prototype.Ya=function(a){var b;if(a.ignoreCase)try{b=new RegExp(a.value,"i")}catch(e){this.log("Invalid regular expression")}else try{b=new RegExp(a.value)}catch(e){this.log("Invalid regular expression")}if(b&&this.a.performance&&this.a.performance.getEntriesByType){a=this.a.performance.getEntriesByType("resource");for(var c=a.length;c--;)if(b.test(a[c].name))return a[c]}return null};d.prototype.Gb=function(a){if((a=this.b.layouts[a.layout])&&
a.categoryRuleSets){a=a.categoryRuleSets;for(var b=0;b<a.length;b++){for(var c=a[b],e=this.ha(c.rules),d=!1,f=0;f<e.length;f++)if(this.qa(e[f])){d=!0;break}if(d){if(c.category)this.m=c.category;else if(c.categoryFromPathParts)this.m=this.Ua(c.categoryFromPathParts);else if(c.categoryFromPathRegexTemplate){if(a=this.ea(c.categoryFromPathRegexTemplate,this.T))this.m=a}else c.categoryFromQueryStringRegexTemplate&&(a=this.ea(c.categoryFromQueryStringRegexTemplate,this.U))&&(this.m=a);break}}}};d.prototype.Ua=
function(a){var b=this.ia(),c;if("depth"in a){b=b.slice(0,a.depth);if(a.titleCase)for(c=b.length;c--;)b[c]=b[c].charAt(0).toUpperCase()+b[c].slice(1).toLowerCase();return b.join(a.separator||"/")}if("template"in a){var e={};for(c=b.length;c--;)e[c.toString()]=b[c];return this.la(a.template,e)}return null};d.prototype.ea=function(a,b){if(b){for(var c={},e=b.length;e--;)c[e.toString()]=b[e];return this.la(a,c)}return null};d.prototype.qa=function(a){for(var b=0;b<a.length;b++){var c=a[b];switch(c.type){case "byHash":if(!this.ra(c))return!1;
break;case "byPath":if(!this.Na(c))return!1;break;case "byPathRegex":if(!this.Pa(c))return!1;break;case "byHashRegex":if(!this.Ja(c))return!1;break;case "byExtendedPath":if(!this.Ha(c))return!1;break;case "byDirectoryCount":if(!this.Fa(c))return!1;break;case "byQueryStringPair":if(!this.Ra(c))return!1;break;case "byQueryStringRegex":if(!this.Ta(c))return!1;break;case "byMarkup":if(!this.La(c))return!1;break;case "matchAny":return!0;default:throw"testCurrentRuleGroup "+c.type+" not understood";}}return!0};
d.prototype.ia=function(){for(var a=this.a.location.pathname.split("/"),b=[],c=0;c<a.length;c++)a[c]&&b.push(a[c]);return b};d.prototype.Fa=function(a){var b=this.ia();return">="===a.operator?b.length>=a.value:">"===a.operator?b.length>a.value:"<="===a.operator?b.length<=a.value:"<"===a.operator?b.length<a.value:b.length===a.value};d.prototype.Ra=function(a){for(var b=this.a.location.search.slice(1).split("&"),c=0;c<b.length;c++){for(var e=b[c].split("="),d=!0,f=0;f<a.value.length;f++)if(a.value[f]!==
e[f]){d=!1;break}if(d)return!0}return!1};d.prototype.Ta=function(a){if(this.a.location.search){var b;try{b=new RegExp(a.value)}catch(c){this.log("Invalid regular expression")}if(b&&(a=b.exec(this.a.location.search)))return this.U=a,!0}return!1};d.prototype.La=function(a){var b,c;if(a=a.value)if(b=a.tag)if(c=this.c.getElementsByTagName(b))for(b=0;b<c.length;b++)if(c[b].innerHTML===a.value)return!0;return!1};d.prototype.Na=function(a){return this.sa(a,this.a.location.pathname)};d.prototype.ra=function(a){return this.sa(a,
this.a.location.hash)};d.prototype.sa=function(a,b){for(var c=[].concat(a.value),e=0;e<c.length;e++){var d=c[e];if("string"===typeof d){if(a.ignoreCase)return d.toLowerCase()===b.toLowerCase();if(d===b)return!0}}return!1};d.prototype.Pa=function(a){var b;try{b=(new RegExp(a.value)).exec(this.a.location.pathname)}catch(c){this.log("Invalid regular expression"),b=null}this.T=b;b=!!b;return"NOT"===a.modifier?!b:b};d.prototype.Ja=function(a){var b;try{b=new RegExp(a.value)}catch(c){return this.log("Invalid regular expression"),
!1}if(b)return b.test(this.a.location.hash)};d.prototype.Ha=function(a){var b=this.a.location.pathname;this.a.location.search?b+=this.a.location.search:this.a.location.hash&&(b+=this.a.location.hash);var c;try{c=new RegExp(a.value)}catch(d){return this.log("Invalid regular expression"),!1}if(c)return c.test(b)};d.prototype.ha=function(a){for(var b=[],c=[],d=0;d<a.length;d++){var g=a[d],f=g.operator;f&&"OR"===f&&(b.push(c),c=[]);c.push(g)}b.push(c);return b};d.prototype.u=function(a){a+="=";for(var b=
this.c.cookie.split(";"),c=b.length,d;c--;){for(d=b[c];" "===d.charAt(0);)d=d.substring(1);if(-1<d.indexOf(a))return d.substring(a.length,d.length)}return null};d.prototype.D=function(a){var b=[a.name+"="+a.value];if(a.F)b.push("Expires=Thu, 01 Jan 1970 00:00:01 GMT");else if("number"===typeof a.B){var c=new Date;c.setTime(c.getTime()+a.B);b.push("Expires="+c.toUTCString())}a.path?b.push("Path="+a.path):b.push("Path=/");a.domain&&b.push("Domain="+a.domain);a.G&&b.push("Secure");this.Va(b.join("; "))};
d.prototype.Va=function(a){this.c.cookie=a};d.prototype.ga=function(){var a=this.u(this.w());if(a){var b=new l;b.l(a);return b}return null};d.prototype.pa=function(a,b){this.D({name:this.w(),value:b,path:a.cookie.path||null,domain:a.cookie.domain,B:this.N("cookieTimeout",this.b,null),G:a.cookie.secure,F:!1})};d.prototype.Ma=function(a){this.pa(a,"")};d.prototype.O=function(a,b){var c=new l,d=this.u(this.w());if(null!==d)c.l(d);else if(d=this.u("cedexisSessionId"))c.w(d),this.D({name:"cedexisSessionId",
value:"",path:a.cookie.path||null,domain:a.cookie.domain,B:null,G:a.cookie.secure,F:!0});c.m(b);this.D({name:this.w(),value:c.v(),path:a.cookie.path||null,domain:a.cookie.domain,B:this.N("cookieTimeout",this.b,null),G:a.cookie.secure,F:!1})};d.prototype.ka=function(){var a=Math.floor(1E9*Math.random()),b=this.a.crypto||this.a.msCrypto;b&&b.getRandomValues&&(a=new Uint32Array(1),b.getRandomValues(a),a=a[0]);b=(new Date).getTime();return new n(a,b,b)};d.prototype.A=function(){return this.g.toString(10)};
d.prototype.vb=function(){var a=this.a.cedexis;if(a){var b=this.l(),a=a.main;b&&a&&(a=a.getDomainPerformance())&&(a={perfData:a,refPage:this.a.location.href},this.g&&(a.sessionID=this.A()),0<Object.keys(this.v).length&&(a.providers=this.v),b.impact(a))}};d.prototype.C=function(a,b){var c={};c[a]=b;this.ma(c)};d.prototype.ma=function(a){var b=this.l();if(b){var c={kpi:[]},d;for(d in a)a.hasOwnProperty(d)&&c.kpi.push([d,a[d]]);this.g&&(c.sessionID=this.A());this.da(c);b.impact(c);this.W&&this.oa(c)}};
d.prototype.wb=function(a){var b=this.l();b&&(a={metadata:a},this.g&&(a.sessionID=this.A()),this.da(a),b.impact(a))};d.prototype.oa=function(a){function b(a,b){b&&(g.dims=g.dims||{},g.dims[a]=b)}function c(a){for(var b=a[0],c=!1,d=b.charAt(0).toLowerCase(),e=1;e<b.length;e++){var f=c?b.charAt(e).toUpperCase():b.charAt(e),c=!1;" "!==f?d+=f:c=!0}g.kpi=g.kpi||{};g.kpi[d]=a[1]}var e=this.l();if(e){var g={client:{type:"JS Impact Plugin",version:d.b}};b("impactSessionId",a.sessionID);b("pageViewId",this.Z);
b("category",a.category);b("source",a.source);if(a.kpi)for(var f=0;f<a.kpi.length;f++)c(a.kpi[f]);e.ajax({url:"//rpt.cedexis.com/impact/"+this.s+"/"+this.o+"?rnd="+m(),method:"post",headers:{Authorization:"some API key","Content-Type":"application/json;charset=UTF-8"},data:this.a.cedexis.jsonEncode(g)})}};d.prototype.da=function(a){this.log("Impact: "+this.a.cedexis.jsonEncode(a))};d.prototype.Za=function(){return this.a.performance&&this.a.performance.getEntriesByType?this.a.performance.getEntriesByType("resource"):
null};d.prototype.mb=function(){var a=this,b=(new Date).getTime(),c=0,d=null;return function(){var g=a.Za();if(g){var f=(new Date).getTime(),h=f-b,p=0;g.length>c?(d=f,c=g.length):p=f-d;5E3<h&&(12E3<h||2E3<p)&&(a.a.clearInterval(a.aa),a.vb())}else a.a.clearInterval(a.aa)}};d.prototype.j=function(a,b){this.H.push([a,b])};d.prototype.M=function(a,b){this.J.push([a,b])};d.prototype.N=function(a,b,c){a=b[a];return"undefined"!==typeof a?a:c};d.prototype.xb=function(a){this.a.clearInterval(a)};d.prototype.la=
function(a,b){for(var c=/(\${(\w+)})/g,d=a,g;null!==(g=c.exec(a))&&g[1]&&g[2];)d=d.replace(g[1],b[g[2]]);return d};d.prototype.nb=function(){var a=this;return function(b){var c=b;"data"in b&&(c=b.data);a.ma(c)}};d.prototype.Ea=function(){return this.a.performance&&"function"===typeof this.a.performance.getEntriesByType};d.prototype.na=function(){var a=this.l();if(a)for(var b=this.L.shift();b;)this.log("Sending: "+JSON.stringify(b)),b={url:"//rpt.cedexis.com/"+this.ca+"/"+this.s+"/"+this.o+"/"+a.requestSignature+
"?rnd="+m(),method:"post",headers:{Authorization:"some API key","Content-Type":"application/json;charset=UTF-8"},data:JSON.stringify(b)},a.ajax(b),b=this.L.shift()};d.prototype.gb=function(){var a=!1,b=this.Sa(),c=this.X();0<q(c).length&&(b.resources=c,a=!0);a=this.Nb(b)||a;a=this.Pb(b)||a;if(a=this.Lb(b,a)||a)b.order=this.Db++,this.L.push(b),this.Y&&this.na();this.f.sampleIntervals&&((a=this.f.sampleIntervals.shift())?this.a.setTimeout(this.ba,a):this.log("Resource checks stopping"))};d.prototype.Lb=
function(a,b){function c(a){return!!(a.performance&&a.performance.timing&&a.performance.timing.loadEventEnd)}function d(a){var b=a.performance.timing,c=[],e=b.navigationStart;c.push(e.toString(36));c.push(Math.max(g(a)-e,0).toString(36));a="loadEventEnd loadEventStart domComplete domContentLoadedEventEnd domContentLoadedEventStart domInteractive domLoading responseEnd responseStart secureConnectionStart connectEnd connectStart domainLookupEnd domainLookupStart fetchStart redirectEnd redirectStart unloadEventEnd unloadEventStart".split(" ");
for(var k=0;k<a.length;k++){var l=b[a[k]]-e;0<l?c.push(l.toString(36)):c.push("0")}return c.join(",")}function g(a){return a.chrome&&a.chrome.loadTimes?(a=a.chrome.loadTimes(),Math.round(1E3*a.firstPaintTime)):a.performance&&a.performance.timing&&a.performance.timing.msFirstPaint?Math.round(a.performance.timing.msFirstPaint):0}return!this.$&&(b||this.R)&&c(this.a)?(this.$=!0,a.plt=d(this.a),!0):!1};d.prototype.Pb=function(a){var b=this.fb(this.Fb);return b?(a.providers=b,!0):!1};d.prototype.Nb=function(a){if(!this.Bb){this.Bb=
!0;var b=this.a.location;a.location={protocol:b.protocol,host:b.host,pathname:b.pathname};return!0}return!1};d.prototype.ja=function(){var a=[],b=this.a.performance.getEntriesByType("resource");if(b)for(var c=0;c<b.length;c++){for(var d=!1,g=b[c],f=0;f<this.K.length;f++)if(this.K[f]===g){d=!0;break}d||(this.K.push(g),this.ib(this.f,g)&&!this.ta(this.f,g)&&a.push(g))}return a};d.prototype.ib=function(a,b){var c;if("object"===typeof a.whitelist)for(var d=0;d<a.whitelist.length;d++){c=null;try{c=new RegExp(a.whitelist[d])}catch(g){this.log(g)}if(c&&
c.test(b.name))return!0}else return!0;return!1};d.prototype.ta=function(a,b){var c;if("object"===typeof a.blacklist)for(var d=0;d<a.blacklist.length;d++){c=null;try{c=new RegExp(a.blacklist[d])}catch(g){this.log(g)}if(c&&c.test(b.name))return!0}return!1};d.prototype.fb=function(a){for(var b=null,c=q(this.v),d=0;d<c.length;d++){var g=c[d],f;a:{f=a.length;for(var h=0;h<f;h++)if(g===a[h]){f=!0;break a}f=!1}f||(a.push(g),b||(b={}),b.providers||(b.providers={}),b.providers[g]=this.v[g])}return b};d.prototype.$a=
function(){function a(a,b,c,d){function e(a){for(var b=a.length,c=[],d=0;d<b;d++){var f=Math.floor(a[d]);0<f?c.push(f.toString(36)):c.push("0")}for(;0<c.length&&"0"===c[c.length-1];)c.pop();return c.join(",")}return{count:a,mean:e(b),sd:e(c),max:e(d)}}function b(a){for(var b=[],c=a.length,e=d.a.length+1,f=0;f<e;f++){for(var g=[],h=0;h<c;h++)g.push(a[h][f]);b.push(t(g))}return b}function c(a){for(var b=[],c=a.length,e=d.a.length+1,f=0;f<e;f++){for(var g=0,h=0;h<c;h++)g=Math.max(g,a[h][f]);b.push(g)}return b}
function e(a,b){for(var c=[],d=a.length,e=b.length,f=0;f<e;f++){for(var g=[],h=0;h<d;h++)g.push(Math.pow(a[h][f]-b[f],2));c.push(Math.sqrt(t(g)))}return c}for(var g=this.ja(),g=function(a,b){for(var c={},e=0;e<b.length;e++){var f=b[e],g=u(a,f.name);if(g){for(var h=c[g.protocol]=c[g.protocol]||{},g=h[g.host]=h[g.host]||[],h=Math.floor(f.startTime),k=[h],l=0;l<d.a.length;l++){var p=Math.floor(f[d.a[l]])-h;0<p?k.push(p):k.push(0)}g.push(k)}}return c}(this.c,g),f=Object.keys(g),h=0;h<f.length;h++)for(var k=
f[h],l=Object.keys(g[k]),r=0;r<l.length;r++){var n=l[r],m=g[k][n],q=b(m),v=e(m,q),w=c(m);g[k][n]=a(m.length,q,v,w)}return g};d.prototype.ab=function(){for(var a={},b=this.ja(),c=0;c<b.length;c++){var e=b[c],g=u(this.c,e.name);if(g){for(var f=a[g.protocol]=a[g.protocol]||{},f=f[g.host]=f[g.host]||{},g=g.pathname+g.search,h=Math.floor(e.startTime),k=[({other:1,img:2,link:3,script:4,css:5,xmlhttprequest:6,video:7,audio:8}[e.initiatorType]||0).toString(36),h.toString(36)],l=0;l<d.a.length;l++){var m=
Math.floor(e[d.a[l]])-h;0<m?k.push(m.toString(36)):k.push("0")}for(;0<k.length&&"0"===k[k.length-1];)k.pop();e=k.join(",");(h=f[g])&&(e=h+"|"+e);f[g]=e}}return a};d.prototype.Sa=function(){var a={pageViewId:this.Z};this.g&&(a.impactSessionId=this.A());return a};d.prototype.lb=function(a){return this.a.cedexis.base64.encode(a+"-"+m())};n.prototype.f=function(){return this.b||this.a};n.prototype.g=function(a){this.b=a};l.prototype.v=function(){return[this.c,this.b,this.a,this.f].join("&")};l.prototype.l=
function(a){a=a.split("&");this.h(a[0]);this.g(a[1]);this.i(a[2]);this.u(a[3])};l.prototype.w=function(a){a=a.split("-");a[0]&&this.h(a[0]);a[1]&&this.g(parseInt(a[1],10).toString(16));a[2]&&this.i(parseInt(a[2],10).toString(16))};l.prototype.m=function(a){a.o()&&(this.c=a.i());a.m()&&(this.b=a.h());a.u()&&(this.a=a.l());a.s()&&(this.f=a.j())};l.prototype.s=function(){return parseInt(this.c,10)};l.prototype.h=function(a){this.c=a};l.prototype.o=function(){return parseInt(this.b,16)};l.prototype.g=
function(a){this.b=a};l.prototype.j=function(){return parseInt(this.a,16)};l.prototype.i=function(a){this.a=a};l.prototype.u=function(a){this.f=a};window.cedexis.classes.SessionCookieChanges=k;k.prototype.o=function(){return"undefined"!==typeof this.b};k.prototype.i=function(){return this.b||null};k.prototype.w=function(a){this.b=a.toString(10)};k.prototype.m=function(){return"undefined"!==typeof this.a};k.prototype.h=function(){return this.a||null};k.prototype.v=function(a){this.a=a.toString(16)};
k.prototype.u=function(){return"undefined"!==typeof this.f};k.prototype.l=function(){return this.f||null};k.prototype.A=function(a){this.f=a.toString(16)};k.prototype.s=function(){return"undefined"!==typeof this.c};k.prototype.j=function(){return this.c||null};k.prototype.g=function(){this.c=(1).toString(10)};var q=Object.keys||function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),
d=c.length;return function(g){if("object"!==typeof g&&("function"!==typeof g||null===g))throw new TypeError("Object.keys called on non-object");var f=[],h;for(h in g)a.call(g,h)&&f.push(h);if(b)for(h=0;h<d;h++)a.call(g,c[h])&&f.push(c[h]);return f}}()})();}());
(function(w,d){
'use strict';
var ImpactKpisPluginClass = w['cedexis']['classes']['ImpactKpisPlugin4'];
var instance = new ImpactKpisPluginClass(w, d, 1, 19300, 1456084070123, {"cookieTimeoutInMs":604800000,"debugging":true,"layouts":{"default":{"categoryRuleSets":[],"kpi":[]}},"legacyPerfDataReportEnabled":false,"sessionTimeoutInMin":44640,"sites":{"www.jumia.com.eg":{"cookie":{"domain":".www.jumia.com.eg"},"layout":"default","sourceConfig":"default"},"www.jumia.com.ng":{"cookie":{"domain":".www.jumia.com.ng"},"layout":"default","sourceConfig":"default"}},"sourceConfigs":{"default":[{"rule":{"type":"referrerDomain","value":"t.co"},"source":"twitter.com","sourceFrom":"sourceProperty"},{"rule":{"allowOwnHost":false,"type":"anyReferrerDomain"}}]}});
if ('addEventListener' in w) { w.addEventListener('message', instance.makeWindowMessageHandler(), false); }
instance.run();
}(window, document));